### ISSUE TITLE
Example pushSingle doesn't work

### ISSUE THREAD

**Issue by card-b** [idw111/push-notification#6]
Example states:

`PushNotification.pushSingle(DeviceType.IOS, iosToken, message, badge, sound, payload);`

This pushes a notification that only plays the sound but has no message displayed because it's missing the "title" arg.

`PushNotification.pushSingle(DeviceType.IOS, iosToken, title, message, badge, sound, payload);`
This works.

**Comment by idw111** [comment]
removed pushSingle, pushMultiple
replaced them with pushToAPN, pushToGCM, or push(..., deviceType)
