### ISSUE TITLE
Deps not being installed

### ISSUE THREAD

**Issue by rorystandley** [idw111/push-notification#8]
I have to manually install these modules for it to work

```
const apn = require('apn');
const gcm = require('node-gcm');
```

**Comment by idw111** [comment]
apn and gcm are described as peer dependency.

https://docs.npmjs.com/files/package.json
> NOTE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. In the next major version of npm (npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead. The behavior in npms 1 & 2 was frequently confusing and could easily put you into dependency hell, a situation that npm is designed to avoid as much as possible.
